spring:
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://www.xcstardust.com:3306/blog
    username: root
    password: 318807

logging:
  level:
    org.springframework: INFO