spring:
  application:
    name: blog-backend
  profiles:
    active: dev
  #session 失效时间
  session:
    timeout: 86400

server:
  port: 8848
  servlet:
    context-path: /api

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

qiniu:
  # 七牛云访问秘钥
  accessKey: BPdbkan5aZEackrnJm7Bk65a5pYvb0QKEBUsTBG_
  # 七牛云密钥
  secretKey: VZhE0sW6zEWLPr0oc6KE1dmOpyW8F6DczIY1W-xv
  # 绑定自己的域名
  domain: img.xcwwq.xyz
  # bucket名称
  bucketName: blog-xc
  #本地 local 七牛云 qiniu  云服务器 online
  UPLOADTYPE: 'qiniu'
  #服务器地址 用于拼接图片显示 可以使用七牛云测试域名 前面请带上http://或者https://根据实际情况带上
  BASEURL: img.xcwwq.xyz

# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: 博客后台接口文档
    description: XC的博客后台接口文档
    version: 1.0
    group:
      default:
        group-name: 博客后台
        api-rule: package
        api-rule-resources:
          - com.xc.blogbackend.controller
logging:
  level:
    com.baomidou.mybatisplus: debug
